name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'branch-api-$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: 🚨 Removed
    label: removed
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies  
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
